/* Headless SchoolKart bot brain: the real js/game.js functions, sliced
   out of the browser IIFE and run against stubbed globals. Shared by
   server/test-ai.js and tools/ai-probe.js. */
"use strict";

var fs = require("fs");
var path = require("path");
var src = fs.readFileSync(path.join(__dirname, "..", "js", "game.js"), "utf8");

function sliceFn(name) {
  var needle = "function " + name + "(";
  var idx = src.indexOf(needle);
  if (idx < 0) throw new Error("missing " + name);
  var i = src.indexOf("{", idx);
  var depth = 0;
  for (var j = i; j < src.length; j++) {
    var c = src[j];
    if (c === "{") depth += 1;
    else if (c === "}") {
      depth -= 1;
      if (depth === 0) return src.slice(idx, j + 1);
    }
  }
  throw new Error("unclosed " + name);
}

function sliceAssign(name) {
  var needle = "var " + name + " = {";
  var idx = src.indexOf(needle);
  if (idx < 0) throw new Error("missing " + name);
  var i = src.indexOf("{", idx);
  var depth = 0;
  for (var j = i; j < src.length; j++) {
    if (src[j] === "{") depth += 1;
    else if (src[j] === "}") {
      depth -= 1;
      if (depth === 0) return src.slice(idx, j + 1) + ";";
    }
  }
  throw new Error("unclosed " + name);
}

var code = [
  "var LAPS = 5;",
  "var MAX_SPEED = 200;",
  "var KPH_PER_UNIT = 3.15;",
  "var TOP_KPH = 200;",
  "var SPEED_LIMIT = TOP_KPH / KPH_PER_UNIT;",
  "var AI_GRIP = 0.9;",
  src.match(/var RACE_MAX_OFF = [0-9.]+;/)[0],
  "var ACCEL = 5;",
  "var BRAKE_DECEL = 6;",
  "var COAST = 2;",
  "var REVERSE_ACCEL = 7;",
  "var REVERSE_MAX = 12;",
  "var LIMP_SPEED = 13;",
  "var LIMP_ACCEL = 2;",
  "var STEER_RATE = 2.35;",
  "var MAX_LAT = 28;",
  "var IDLE_FUEL = 0.46;",
  "var THROTTLE_FUEL = 0.12;",
  "var PIT_HOLD = 2.5;",
  "var PIT_ENTRY_V = 18;",
  "var GETAWAY_T = 1.5;",
  "var REV_SWEET_LO = 0.58;",
  "var REV_SWEET_HI = 0.8;",
  "var REV_GREAT_LO = 0.64;",
  "var REV_GREAT_HI = 0.74;",
  "var ASPHALT = 8.6;",
  "var RUNOFF = 3.8;",
  "var KERB_NAMES = ['the90', 'hairpin', 'chicane', 'sweeper', 'kink'];",
  "var CAMPUS_KERBS = ['the90', 'hairpin', 'chicane', 'sweeper', 'kink'];",
  sliceAssign("BUILTIN_KERBS"),
  sliceFn("setTrackKerbs"),
  "var KERB_RAISE = 0.055;",
  "var GRASS_MAX = 8.5;",
  "var GRASS_ROLL = 4;",
  "var GRASS_DUMP = 40;",
  "var TIRE_FLOOR = 22;",
  "var WORN_FEEL = 0.38 + 0.62 * (TIRE_FLOOR / 100);",
  "var MESH_NOSE = 3.55;",
  "var MESH_TAIL = 2.1;",
  "var MESH_HALF_W = 1.2;",
  "var SF_Z = -80;",
  "var PIT_ENTRY = { x0: 8, x1: 28, z0: -70.0, z1: -61.0 };",
  "var PIT_EXIT = { x0: 128, x1: 160, z0: -68.0, z1: -58.0 };",
  "var PIT_LANE = { x0: 28, x1: 136, z0: -61.5, z1: -52.5 };",
  "var PIT_GRAB = { x0: 64, x1: 98, z0: -61.0, z1: -53.2 };",
  "var PIT_PAVE = [PIT_ENTRY, PIT_LANE, PIT_GRAB, PIT_EXIT];",
  "var PIT_PATH = [];",
  "var PIT_HALF = 4.5;",
  "var PIT_META = { ax: 28, az: -57, bx: 136, bz: -57, on: true };",
  "var PATH = [];",
  "var MAP_SURF = [];",
  "var MAP_CLOSED = false;",
  "var TRACK_LEN = 0;",
  "var _x = -200;",
  "var _z = SF_Z;",
  "var _h = 0;",
  "var _y = 0;",
  "var stampTrees = [];",
  "var RIBBON_SEGS = 360;",
  "var trackCode = '';",
  "var state = 'racing';",
  "var raceTime = 0;",
  "var launchT = 0;",
  "var launchMul = 1;",
  "var mpMode = false;",
  "var remotes = {};",
  "var hostBots = {};",
  "var player = { x: -9999, z: -9999, heading: 0, speed: 0, kind: 'player', mesh: { visible: false }, finished: false, pitServicing: false };",
  "var cpus = [];",
  "var FUEL_OVERRIDE = 0;",
  "function setFuelOverride(v) { FUEL_OVERRIDE = v; }",
  // A/B-ing a brain change is meaningless if the run wanders. The only
  // randomness the sim reaches is the worn-tire twitch, so pin it.
  "var _seed = 1;",
  "function setSeed(v) { _seed = (v >>> 0) || 1; }",
  "var TRACE_CAR = '';",
  "function setTraceCar(n) { TRACE_CAR = n || ''; }",
  "var Math = Object.create(global.Math);",
  "Math.random = function () { _seed = (_seed * 1103515245 + 12345) & 0x7fffffff; return _seed / 0x7fffffff; };",
  sliceFn("clamp"),
  sliceFn("inRect"),
  sliceFn("pitSegLine"),
  sliceFn("pitSegArc"),
  sliceFn("pitLine"),
  sliceFn("pitArc"),
  sliceFn("pitSBend"),
  sliceFn("onPitPath"),
  sliceFn("pointOnPitPath"),
  sliceFn("pitPathAhead"),
  sliceFn("buildCampusPitPath"),
  sliceFn("buildCustomPitPath"),
  sliceFn("rebuildPitPath"),
  sliceFn("onPitPavement"),
  sliceFn("closestOnSeg"),
  sliceFn("closestOnArc"),
  sliceFn("addLine"),
  sliceFn("addArc"),
  sliceFn("pathLine"),
  sliceFn("pathArc"),
  sliceFn("pathSnap"),
  sliceFn("resetPathCursor"),
  sliceFn("parkPitMouths"),
  sliceFn("setDefaultPit"),
  sliceFn("clearPit"),
  sliceFn("turnWrap"),
  sliceFn("joinPlan"),
  sliceFn("emitJoin"),
  src.match(/var JOIN_APART = [0-9.]+;/)[0],
  sliceFn("joinClearance"),
  sliceFn("autoClosePath"),
  sliceFn("cornerKind"),
  sliceFn("buildCampusPath"),
  sliceFn("flattenCloseToZero"),
  sliceFn("goTo"),
  sliceFn("closeWithSweeper"),
  sliceFn("buildHarborPath"),
  sliceFn("buildParkPath"),
  sliceFn("buildDesertPath"),
  sliceFn("buildForestPath"),
  sliceFn("pointOnSeg"),
  sliceFn("centerlinePoint"),
  sliceFn("projectOn"),
  sliceFn("trackInfoAt"),
  src.match(/var HINT_SLACK = [0-9.]+;/)[0],
  sliceFn("projectTrackNear"),
  sliceFn("projectTrack"),
  "var WALLS = [];",
  sliceFn("wallSeg"),
  sliceFn("skipLeftBarrier"),
  sliceFn("wallKindFor"),
  src.match(/var DECK_APART = [0-9.]+;/)[0],
  sliceFn("carDeckY"),
  sliceFn("sameDeck"),
  sliceFn("wallCutsRibbon"),
  sliceFn("joinColinearWall"),
  sliceFn("mergeColinearWalls"),
  sliceFn("placeWalls"),
  sliceFn("pitRoadDist"),
  sliceFn("raceRoadDist"),
  sliceFn("pitClaims"),
  sliceFn("inPitLane"),
  sliceFn("inPitGrab"),
  sliceFn("isDriveableLoop"),
  sliceAssign("LAP_ORIGIN"),
  sliceFn("lapOriginS"),
  sliceFn("scoreLap"),
  sliceFn("updateLaps"),
  sliceFn("rideHeight"),
  sliceFn("steerWheelYaw"),
  sliceFn("onLongStraight"),
  sliceFn("pathSegAt"),
  sliceFn("inChicaneS"),
  sliceFn("wheelWorld"),
  sliceFn("kerbDepthAt"),
  sliceFn("sampleWheelKerbs"),
  sliceFn("applyMotion"),
  src.match(/var DEFEND_MOVE = [0-9.]+;/)[0],
  src.match(/var DEFEND_REST = [0-9.]+;/)[0],
  sliceAssign("AI_AGGRO"),
  sliceAssign("AI_SMART"),
  sliceAssign("AI_TIDY"),
  sliceAssign("AI_MESSY"),
  sliceAssign("AI_SHY"),
  sliceAssign("AI_BEAT"),
  sliceAssign("AI_LAB"),
  sliceAssign("AI_WILD"),
  sliceAssign("AI_WIDE"),
  "var _scan = { dHair: 999, dChi: 999, dTight: 999, tightR: 99, dBend: 999, bendR: 99, inside: 1 };",
  sliceFn("aiOf"),
  sliceFn("scanAhead"),
  sliceFn("tireFeelOf"),
  sliceFn("brakeDecelAt"),
  sliceFn("apexFromRadius"),
  sliceFn("apexLimit"),
  sliceFn("eachRival"),
  sliceFn("avoidRams"),
  "var _prey = { r: null, d: 999, fwd: 0, lat: 0 };",
  "var _hunt = { on: false, tx: 0, tz: 0, want: 0, noLift: false, dive: false, catchUp: false, block: false, pass: false, cover: 0, gap: 0, draft: false };",
  sliceAssign("RACE"),
  sliceFn("aiWrap"),
  sliceFn("raceDeltaS"),
  sliceFn("raceKey"),
  sliceFn("ensureRaceBrain"),
  sliceFn("bakeRaceBrain"),
  sliceFn("profilePasses"),
  sliceFn("lapFuel"),
  sliceFn("lapFrac"),
  sliceFn("trackBurn"),
  sliceFn("burnPerLap"),
  sliceFn("raceAt"),
  sliceFn("raceVAt"),
  sliceFn("paceV"),
  sliceFn("raceWantAhead"),
  sliceFn("raceProg"),
  sliceFn("trackGap"),
  sliceAssign("PIT_MOUTH"),
  sliceFn("pitMouthS"),
  sliceFn("pitDelta"),
  sliceAssign("PIT_SIDE"),
  sliceFn("pitSide"),
  sliceFn("trackLeadGap"),
  sliceFn("catchBonus"),
  sliceFn("faceDot"),
  sliceAssign("WALL_GRID"),
  sliceFn("wallGrid"),
  sliceFn("wallsNear"),
  sliceFn("noseBlocked"),
  sliceFn("recoverSteer"),
  sliceFn("pickPrey"),
  sliceFn("followLimit"),
  sliceFn("laneClear"),
  sliceFn("passSide"),
  sliceFn("planHunt"),
  sliceFn("gradeLaunch"),
  sliceFn("carCorners"),
  sliceFn("projectCorners"),
  sliceFn("meshOverlap"),
  sliceFn("hitKeepYaw"),
  sliceFn("hitCarFeel"),
  sliceFn("bashCars"),
  "function puffHit() {}",
  "function spawnFx() {}",
  "function dumpLaunch() {}",
  "function applyCpuLaunch(r) { r.launchArmed = true; r.launchMul = 1; r.launchT = 0; }",
  sliceFn("coolDown"),
  sliceFn("jammedByTraffic"),
  sliceFn("resetOnLine"),
  sliceFn("updateCpu"),
  sliceFn("isDriveableLoop"),
  "function poseCar(r) { if (r.mesh) { r.mesh.position.x = r.x; r.mesh.position.z = r.z; } }",
  "function trackLen() { return TRACK_LEN; }",
  "function pathDump() { return PATH.map(function (s) { return { type: s.type, name: s.name, startS: s.startS, len: s.len, r: s.r, deg: s.type === 'arc' ? ((s.a1 - s.a0) * 180) / Math.PI : 0 }; }); }",
  // rebuildPath() re-points the kerb list on every rebuild. Skip that here
  // and a custom loop inherits the last circuit's kerb naming, so the same
  // seed on the same board grips differently depending on what ran before.
  "function sealCustom() { MAP_CLOSED = true; MAP_SURF = PATH.slice(); setTrackKerbs('campus'); }",
  "function restoreCampus() {",
  "  MAP_CLOSED = false;",
  "  MAP_SURF = [];",
  "  resetPathCursor();",
  "  setDefaultPit();",
  "  buildCampusPath();",
  "}",
  // Same dispatch rebuildPath() uses for the reserved circuit codes, so
  // the probe and the tests exercise the shipped geometry.
  "function buildBuiltin(id) {",
  "  MAP_CLOSED = false;",
  "  MAP_SURF = [];",
  "  resetPathCursor();",
  "  setDefaultPit();",
  "  setTrackKerbs(id);",
  "  if (id === 'harbor') buildHarborPath();",
  "  else if (id === 'park') buildParkPath();",
  "  else if (id === 'desert') buildDesertPath();",
  "  else if (id === 'forest') buildForestPath();",
  "  else buildCampusPath();",
  "  placeWalls();",
  "}",
  "setDefaultPit();",
  "buildCampusPath();",
  "return {",
  "  TRACK_LEN: TRACK_LEN,",
  "  PATH: PATH,",
  // PATH is reassigned on every rebuild, so a captured reference goes
  // stale the moment a test switches track. Ask for it live instead.
  "  pathNow: function () { return PATH; },",
  "  runBot: runBot,",
  "  runField: runField,",
  "  setFuelOverride: setFuelOverride,",
  "  setSeed: setSeed,",
  "  setTraceCar: setTraceCar,",
  "  runTrace: runTrace,",
  "  SPEED_LIMIT: SPEED_LIMIT,",
  "  runHunt: runHunt,",
  "  runCatch: runCatch,",
  "  runLongCatch: runLongCatch,",
  "  runBlock: runBlock,",
  "  runPass: runPass,",
  "  buildWideLoop: buildWideLoop,",
  "  resetPathCursor: resetPathCursor,",
  "  pathLine: pathLine,",
  "  pathArc: pathArc,",
  "  clearPit: clearPit,",
  "  setDefaultPit: setDefaultPit,",
  "  buildCampusPath: buildCampusPath,",
  "  buildBuiltin: buildBuiltin,",
  "  autoClosePath: autoClosePath,",
  "  bashCars: bashCars,",
  "  apexFromRadius: apexFromRadius,",
  "  gradeLaunch: gradeLaunch,",
  "  centerlinePoint: centerlinePoint,",
  "  projectTrack: projectTrack,",
  "  projectTrackNear: projectTrackNear,",
  "  closestOnSeg: closestOnSeg,",
  "  closestOnArc: closestOnArc,",
  "  raceDeltaS: raceDeltaS,",
  "  scanAhead: scanAhead,",
  "  apexLimit: apexLimit,",
  "  bakeRaceBrain: bakeRaceBrain,",
  "  raceAt: raceAt,",
  "  raceVAt: raceVAt,",
  "  paceV: paceV,",
  "  raceWantAhead: raceWantAhead,",
  "  trackGap: trackGap,",
  "  catchBonus: catchBonus,",
  "  noseBlocked: noseBlocked,",
  "  carDeckY: carDeckY,",
  "  faceDot: faceDot,",
  "  runRecover: runRecover,",
  "  runWallStuck: runWallStuck,",
  "  RACE: RACE,",
  "  trackLen: trackLen,",
  "  pathDump: pathDump,",
  "  sealCustom: sealCustom,",
  "  restoreCampus: restoreCampus,",
  "  isDriveableLoop: isDriveableLoop,",
  "  pitRoadDist: pitRoadDist,",
  "  pitClaims: pitClaims,",
  "  inPitLane: inPitLane,",
  "  inPitGrab: inPitGrab,",
  "  WALLS: WALLS,",
  "  placeWalls: placeWalls,",
  "  AI_AGGRO: AI_AGGRO,",
  "  AI_SMART: AI_SMART,",
  "  AI_TIDY: AI_TIDY,",
  "  AI_MESSY: AI_MESSY,",
  "  AI_SHY: AI_SHY,",
  "  AI_BEAT: AI_BEAT,",
  "  AI_LAB: AI_LAB,",
  "  AI_WILD: AI_WILD,",
  "  AI_WIDE: AI_WIDE",
  "};",
  "function runBot(name, gridX, gridZ, s0, seconds, heading) {",
  "  var r = {",
  "    kind: 'cpu', name: name,",
  "    x: gridX, z: gridZ, heading: heading || 0, speed: 0, slide: 0,",
  "    fuel: 100, tires: 100, lap: 1, passedHalf: false, lastX: gridX, s: s0, lastS: s0,",
  "    brakeHold: 0, finished: false, finishTime: 0,",
  "    wantPit: false, didPit: false, pitServicing: false, pitTimer: 0, pitUsedVisit: false,",
    "    launchMul: 1, launchT: 0, launchArmed: true, aiT: 0, aiStuck: 0, pitExitT: 0,",
  "    mesh: { visible: true, position: { x: gridX, y: 0, z: gridZ, set: function(x,y,z){ this.x=x; this.y=y; this.z=z; } }, rotation: { set: function(){}, x:0, y:0, z:0 }, userData: {} }",
  "  };",
  "  var dt = 1/30;",
  "  var grass = 0, asphalt = 0, emptyT = 0, pitStops = 0, maxOff = 0;",
  "  var hairFast = 0, reverseT = 0, boxT = 0;",
  "  var wasBox = false;",
  "  var grassBy = {};",
  "  var pitAt = null;",
  "  raceTime = 0;",
  "  for (var t = 0; t < seconds; t += dt) {",
  "    raceTime = t;",
  "    updateCpu(r, dt);",
  "    if (r.pitServicing) boxT += dt;",
  "    if (r.pitServicing && !wasBox) { pitStops += 1; pitAt = { t: t, lap: r.lap, fuel: r.fuel }; }",
  "    wasBox = r.pitServicing;",
  "    var info = projectTrack(r.x, r.z);",
  "    if (info.grass) { grass += dt; grassBy[info.name] = (grassBy[info.name] || 0) + dt; }",
  "    else asphalt += dt;",
  "    if (info.dist > maxOff) maxOff = info.dist;",
  "    if (info.name === 'hairpin' && !info.grass && r.speed > 17) hairFast += dt;",
  "    if (r.fuel <= 0) emptyT += dt;",
  "    if (r.speed < 0) reverseT += dt;",
  "    if (r.finished) break;",
  "  }",
  "  return {",
  "    name: name, finished: r.finished, finishTime: r.finishTime || raceTime,",
  "    lap: r.lap, fuel: r.fuel, tires: r.tires, didPit: r.didPit, pitStops: pitStops, pitAt: pitAt,",
  "    grass: grass, asphalt: asphalt, maxOff: maxOff, emptyT: emptyT, grassBy: grassBy,",
  "    hairFast: hairFast, reverseT: reverseT, boxT: boxT, x: r.x, z: r.z, speed: r.speed",
  "  };",
  "}",
  "function makeBot(name, x, z, s0, heading) {",
  "  return {",
  "    kind: 'cpu', name: name,",
  "    x: x, z: z, heading: heading || 0, speed: 0, slide: 0,",
  "    fuel: 100, tires: 100, lap: 1, passedHalf: false, lastX: x, s: s0, lastS: s0,",
  "    brakeHold: 0, finished: false, finishTime: 0,",
  "    wantPit: false, didPit: false, pitServicing: false, pitTimer: 0, pitUsedVisit: false,",
  "    launchMul: 1, launchT: 0, launchArmed: true, aiT: 0, pitExitT: 0,",
  "    mesh: { visible: true, position: { x: x, y: 0, z: z, set: function(a,b,c){ this.x=a; this.y=b; this.z=c; } }, rotation: { set: function(){}, x:0, y:0, z:0 }, userData: {} }",
  "  };",
  "}",
  // A whole field on one ribbon: same updateCpu, same 3-pass bashCars
  // the live loop runs. Single-bot runs can never show a jam or a train.
  "function runField(names, seconds, spawn) {",
  "  var i, j, pass;",
  "  var bots = [];",
  "  for (i = 0; i < names.length; i++) {",
  "    var s0 = spawn ? spawn.s - i * 8 : TRACK_LEN - 6 - i * 8;",
  "    var gp = centerlinePoint(s0);",
  "    var side = i % 2 ? 2.7 : -2.7;",
  "    bots.push(makeBot(names[i], gp.x - Math.sin(gp.h) * side, gp.z + Math.cos(gp.h) * side, s0, gp.h));",
  "  }",
  "  if (FUEL_OVERRIDE) for (i = 0; i < bots.length; i++) bots[i].fuel = FUEL_OVERRIDE;",
  "  cpus = bots;",
  "  var dt = 1/30;",
  "  var stat = [];",
  "  for (i = 0; i < bots.length; i++) {",
  "    stat.push({ name: names[i], grass: 0, offTrack: 0, reverseT: 0, maxSpeed: 0, maxOff: 0, pitStops: 0, wasBox: false, emptyT: 0, still: 0, contacts: 0, contactT: 0, peelT: 0 });",
  "  }",
  "  raceTime = 0;",
  "  var resetLog = [];",
  "  var carLog = [];",
  "  var t;",
  "  for (t = 0; t < seconds; t += dt) {",
  "    raceTime = t;",
  "    var done = true;",
  "    for (i = 0; i < bots.length; i++) {",
  "      if (!bots[i].finished) done = false;",
  "      var was = bots[i].aiResets || 0;",
  "      var v0 = bots[i].speed;",
  "      var pj = projectTrack(bots[i].x, bots[i].z);",
  "      updateCpu(bots[i], dt);",
  "      if ((bots[i].aiResets || 0) > was && resetLog.length < 60) {",
  "        resetLog.push({ name: names[i], t: t, s: pj.s, name2: pj.name, dist: pj.dist, speed: v0, lap: bots[i].lap, wantPit: !!bots[i].wantPit, didPit: !!bots[i].didPit, pit: inPitLane(bots[i]) || inPitGrab(bots[i]) });",
  "      }",
  "      if (TRACE_CAR && (TRACE_CAR === '*' || names[i] === TRACE_CAR)) {",
  "        var b = bots[i];",
  "        carLog.push({ t: t, who: names[i], s: b.s, x: b.x, z: b.z, gs: projectTrack(b.x, b.z).s, dist: pj.dist, name2: pj.name, v: b.speed, stuckT: b.aiStuckT || 0, revT: b.aiRevT || 0,",
  "          grass: !!pj.grass, blocked: noseBlocked(b), wrong: Math.cos(aiWrap(b.heading - pj.h)), lap: b.lap,",
  "          wantPit: !!b.wantPit, inLane: inPitLane(b), serv: !!b.pitServicing, hitT: b.aiHitT || 0, resets: b.aiResets || 0, fuel: b.fuel });",
  "      }",
  "    }",
  "    for (pass = 0; pass < 3; pass++) {",
  "      for (i = 0; i < bots.length; i++) {",
  "        for (j = i + 1; j < bots.length; j++) bashCars(bots[i], bots[j]);",
  "      }",
  "    }",
  "    for (i = 0; i < bots.length; i++) {",
  "      var r = bots[i];",
  "      var st = stat[i];",
  "      if (r.finished) continue;",
  "      if (r.aiHitT > 0.44) st.contacts += 1;",
  "      if (r.aiHitT > 0) st.contactT += dt;",
  "      if (r.wantPit && !r.pitServicing) st.peelT += dt;",
  "      var info = projectTrack(r.x, r.z);",
  "      if (info.grass) st.grass += dt;",
  "      if (info.dist > ASPHALT + 0.5 && !inPitLane(r) && !inPitGrab(r)) st.offTrack += dt;",
  "      if (info.dist > st.maxOff) st.maxOff = info.dist;",
  "      if (Math.abs(r.speed) > st.maxSpeed) st.maxSpeed = Math.abs(r.speed);",
  "      if (r.speed < -0.2) st.reverseT += dt;",
  "      if (Math.abs(r.speed) < 0.6 && !r.pitServicing) st.still += dt;",
  "      if (r.fuel <= 0) st.emptyT += dt;",
  "      if (r.pitServicing && !st.wasBox) st.pitStops += 1;",
  "      st.wasBox = r.pitServicing;",
  "    }",
  "    if (done) break;",
  "  }",
  "  var out = [];",
  "  for (i = 0; i < bots.length; i++) {",
  "    out.push({",
  "      name: names[i], finished: bots[i].finished, finishTime: bots[i].finishTime || raceTime,",
  "      lap: bots[i].lap, didPit: bots[i].didPit, pitStops: stat[i].pitStops,",
  "      resets: bots[i].aiResets || 0, grass: stat[i].grass, offTrack: stat[i].offTrack,",
  "      reverseT: stat[i].reverseT, still: stat[i].still, maxSpeed: stat[i].maxSpeed,",
  "      maxOff: stat[i].maxOff, emptyT: stat[i].emptyT, contacts: stat[i].contacts,",
  "      contactT: stat[i].contactT, peelT: stat[i].peelT,",
  "      fuel: bots[i].fuel, tires: bots[i].tires",
  "    });",
  "  }",
  "  cpus = [];",
  "  out.sort(function (a, b) { return (b.lap - a.lap) || (a.finishTime - b.finishTime); });",
  "  out.resetLog = resetLog;",
  "  out.carLog = carLog;",
  "  return out;",
  "}",
  // One clean bot, alone, sampled against its own speed profile. This is
  // how you find out whether a slow lap is the plan or the driving.
  "function runTrace(name, seconds) {",
  "  var s0 = 12;",
  "  var gp = centerlinePoint(s0);",
  "  var r = makeBot(name, gp.x, gp.z, s0, gp.h);",
  "  r.fuel = FUEL_OVERRIDE ? FUEL_OVERRIDE : 1e6;",
  "  cpus = [r];",
  "  var p = aiOf(r);",
  "  var dt = 1/30;",
  "  var samples = [];",
  "  var names = [];",
  "  var lapT = 0, lap1 = 0, best = 1e9, lastLap = 1, laps = 0, pitLap = false;",
  "  var lapLog = [];",
  "  raceTime = 0;",
  "  for (var t = 0; t < seconds; t += dt) {",
  "    raceTime = t;",
  "    lapT += dt;",
  "    var s0 = r.s;",
  "    var pit = r.pitServicing || inPitLane(r) || inPitGrab(r) || r.wantPit;",
  "    if (pit) pitLap = true;",
  "    updateCpu(r, dt);",
  "    if (r.lap > lastLap) {",
  "      laps += 1;",
  "      if (!lap1) lap1 = lapT;",
  "      if (!pitLap && lapT < best) best = lapT;",
  "      lapLog.push({ t: lapT, pit: pitLap, tires: r.tires, fuel: r.fuel });",
  "      lastLap = r.lap; lapT = 0; pitLap = false;",
  "    }",
  "    if (r.finished) { laps += 1; lapLog.push({ t: lapT, pit: pitLap, tires: r.tires, fuel: r.fuel }); break; }",
  "    var step = raceDeltaS(r.s, s0);",
  "    if (step < 0 || step > 12) step = 0;",
  "    var pj2 = projectTrack(r.x, r.z);",
  "    samples.push({ s: r.s, dt: dt, ds: step, pit: pit, v: Math.abs(r.speed), prof: paceV(raceVAt(r.s, clamp(r.tires/100,0,1)), p),",
  "      dist: pj2.dist, grass: !!pj2.grass, blocked: noseBlocked(r), wrong: Math.cos(aiWrap(r.heading - pj2.h)), stuckT: r.aiStuckT || 0, resets: r.aiResets || 0, name: pj2.name,",
  "      wantPit: !!r.wantPit, mouthD: pitDelta(r), inLane: inPitLane(r), serv: !!r.pitServicing, fuel: r.fuel, lap: r.lap });",
  "    var bi = Math.floor(r.s / 40);",
  "    if (!names[bi]) names[bi] = centerlinePoint(r.s).name;",
  "  }",
  "  cpus = [];",
  "  return { samples: samples, names: names, laps: laps, lap1: lap1, best: best === 1e9 ? 0 : best, lapLog: lapLog, fuel: r.fuel, tires: r.tires };",
  "}",
  "function blankBot(name, x, z, spd) {",
  "  return {",
  "    kind: 'cpu', name: name, x: x, z: z, heading: 0, speed: spd, slide: 0,",
  "    fuel: 100, tires: 100, lap: 1, passedHalf: false, lastX: x, s: TRACK_LEN - 14, lastS: TRACK_LEN - 14,",
  "    brakeHold: 0, finished: false, finishTime: 0,",
  "    wantPit: false, didPit: false, pitServicing: false, pitTimer: 0, pitUsedVisit: false,",
    "    launchMul: 1, launchT: 0, launchArmed: true, aiT: 0, aiStuck: 0, pitExitT: 0,",
  "    mesh: { visible: true, position: { x: x, y: 0, z: z, set: function(a,b,c){ this.x=a; this.y=b; this.z=c; } }, rotation: { set: function(){}, x:0, y:0, z:0 }, userData: {} }",
  "  };",
  "}",
  "function runHunt(name, seconds) {",
  "  player.x = 10; player.z = SF_Z; player.heading = 0; player.speed = 20;",
  "  player.kind = 'player'; player.finished = false; player.pitServicing = false;",
  "  player.mesh = { visible: true };",
  "  var r = blankBot(name, -4, SF_Z + 0.2, 26);",
  "  var d0 = Math.hypot(player.x - r.x, player.z - r.z);",
  "  var minD = d0;",
  "  var hitT = 0;",
  "  var dt = 1/30;",
  "  raceTime = 2;",
  "  for (var t = 0; t < seconds; t += dt) {",
  "    player.x += Math.cos(player.heading) * player.speed * dt;",
  "    player.z += Math.sin(player.heading) * player.speed * dt;",
  "    updateCpu(r, dt);",
  "    var d = Math.hypot(player.x - r.x, player.z - r.z);",
  "    if (d < minD) minD = d;",
  "    if (d < 2.55) hitT += dt;",
  "  }",
  "  var endD = Math.hypot(player.x - r.x, player.z - r.z);",
  "  player.x = -9999; player.z = -9999; player.mesh.visible = false;",
  "  return { name: name, d0: d0, minD: minD, endD: endD, hitT: hitT };",
  "}",
  "function runLongCatch(name, seconds) {",
  "  player.x = 200; player.z = SF_Z; player.heading = 0; player.speed = 32;",
  "  player.kind = 'player'; player.finished = false; player.pitServicing = false;",
  "  player.mesh = { visible: true };",
  "  var r = blankBot(name, -6, SF_Z + 0.2, 30);",
  "  var d0 = Math.hypot(player.x - r.x, player.z - r.z);",
  "  var minD = d0;",
  "  var dt = 1/30;",
  "  raceTime = 2;",
  "  for (var t = 0; t < seconds; t += dt) {",
  "    player.x += Math.cos(player.heading) * player.speed * dt;",
  "    player.z += Math.sin(player.heading) * player.speed * dt;",
  "    updateCpu(r, dt);",
  "    var d = Math.hypot(player.x - r.x, player.z - r.z);",
  "    if (d < minD) minD = d;",
  "  }",
  "  var endD = Math.hypot(player.x - r.x, player.z - r.z);",
  "  player.x = -9999; player.z = -9999; player.mesh.visible = false;",
  "  return { name: name, d0: d0, minD: minD, endD: endD, speed: r.speed };",
  "}",
  "function runCatch(name, seconds) {",
  "  player.x = 52; player.z = SF_Z; player.heading = 0; player.speed = 30;",
  "  player.kind = 'player'; player.finished = false; player.pitServicing = false;",
  "  player.mesh = { visible: true };",
  "  var r = blankBot(name, -6, SF_Z + 0.2, 28);",
  "  var d0 = Math.hypot(player.x - r.x, player.z - r.z);",
  "  var minD = d0;",
  "  var dt = 1/30;",
  "  raceTime = 2;",
  "  for (var t = 0; t < seconds; t += dt) {",
  "    player.x += Math.cos(player.heading) * player.speed * dt;",
  "    player.z += Math.sin(player.heading) * player.speed * dt;",
  "    updateCpu(r, dt);",
  "    var d = Math.hypot(player.x - r.x, player.z - r.z);",
  "    if (d < minD) minD = d;",
  "  }",
  "  var endD = Math.hypot(player.x - r.x, player.z - r.z);",
  "  player.x = -9999; player.z = -9999; player.mesh.visible = false;",
  "  return { name: name, d0: d0, minD: minD, endD: endD, speed: r.speed };",
  "}",
  "function runBlock(name, seconds) {",
  "  player.x = 4; player.z = SF_Z + 2.4; player.heading = 0; player.speed = 38;",
  "  player.kind = 'player'; player.finished = false; player.pitServicing = false;",
  "  player.mesh = { visible: true };",
  "  var r = blankBot(name, 18, SF_Z, 32);",
  "  var h0 = r.heading;",
  "  var x0 = r.x;",
  "  var z0 = r.z;",
  "  var maxAbsH = 0;",
  "  var dt = 1/30;",
  "  raceTime = 2;",
  "  for (var t = 0; t < seconds; t += dt) {",
  "    player.x += Math.cos(player.heading) * player.speed * dt;",
  "    player.z += Math.sin(player.heading) * player.speed * dt;",
  "    updateCpu(r, dt);",
  "    var ah = Math.abs(r.heading);",
  "    if (ah > Math.PI) ah = Math.abs(ah - Math.PI * 2);",
  "    if (ah > maxAbsH) maxAbsH = ah;",
  "  }",
  "  player.x = -9999; player.z = -9999; player.mesh.visible = false;",
  "  return { name: name, x0: x0, z0: z0, x: r.x, z: r.z, heading: r.heading, maxAbsH: maxAbsH, speed: r.speed, h0: h0 };",
  "}",
  "function runPass(name, seconds) {",
  "  player.x = 18; player.z = SF_Z; player.heading = 0; player.speed = 22;",
  "  player.kind = 'player'; player.finished = false; player.pitServicing = false;",
  "  player.mesh = { visible: true };",
  "  var r = blankBot(name, -8, SF_Z + 0.15, 34);",
  "  var d0 = Math.hypot(player.x - r.x, player.z - r.z);",
  "  var minD = d0;",
  "  var maxAbsLat = 0;",
  "  var dt = 1/30;",
  "  raceTime = 2;",
  "  for (var t = 0; t < seconds; t += dt) {",
  "    player.x += Math.cos(player.heading) * player.speed * dt;",
  "    player.z += Math.sin(player.heading) * player.speed * dt;",
  "    updateCpu(r, dt);",
  "    var rx = player.x - r.x;",
  "    var rz = player.z - r.z;",
  "    var d = Math.hypot(rx, rz);",
  "    if (d < minD) minD = d;",
  "    var lat = -rx * Math.sin(r.heading) + rz * Math.cos(r.heading);",
  "    if (Math.abs(lat) > maxAbsLat) maxAbsLat = Math.abs(lat);",
  "  }",
  "  var endD = Math.hypot(player.x - r.x, player.z - r.z);",
  "  var fx = Math.cos(r.heading);",
  "  var fz = Math.sin(r.heading);",
  "  var endFwd = (player.x - r.x) * fx + (player.z - r.z) * fz;",
  "  player.x = -9999; player.z = -9999; player.mesh.visible = false;",
  "  return { name: name, d0: d0, minD: minD, endD: endD, maxAbsLat: maxAbsLat, endFwd: endFwd, x: r.x, speed: r.speed };",
  "}",
  "function runRecover(name, seconds) {",
  "  var r = blankBot(name, 0, SF_Z - 14, 3);",
  "  r.heading = -Math.PI * 0.5;",
  "  r.s = projectTrack(r.x, r.z).s;",
  "  var d0 = projectTrack(r.x, r.z).dist;",
  "  var grass = 0, reverseT = 0, minDist = d0;",
  "  var dt = 1/30;",
  "  raceTime = 2;",
  "  for (var t = 0; t < seconds; t += dt) {",
  "    var spd0 = r.speed;",
  "    updateCpu(r, dt);",
  "    var info = projectTrack(r.x, r.z);",
  "    if (info.dist < minDist) minDist = info.dist;",
  "    if (info.grass) grass += dt;",
  "    if (r.speed < -0.4 || (spd0 >= 0 && r.speed < 0)) reverseT += dt;",
  "  }",
  "  var end = projectTrack(r.x, r.z);",
  "  return { name: name, d0: d0, dist: end.dist, minDist: minDist, grass: grass, onAsphalt: !!end.onAsphalt, reverseT: reverseT, speed: r.speed };",
  "}",
  "function runWallStuck(name, seconds) {",
  "  placeWalls();",
  "  var r = blankBot(name, 0, SF_Z - 11.2, 6);",
  "  r.heading = -Math.PI * 0.5;",
  "  r.s = projectTrack(r.x, r.z).s;",
  "  var d0 = projectTrack(r.x, r.z).dist;",
  "  var reverseT = 0, minDist = d0;",
  "  var dt = 1/30;",
  "  raceTime = 2;",
  "  for (var t = 0; t < seconds; t += dt) {",
  "    updateCpu(r, dt);",
  "    var info = projectTrack(r.x, r.z);",
  "    if (info.dist < minDist) minDist = info.dist;",
  "    if (r.speed < -0.2) reverseT += dt;",
  "  }",
  "  var end = projectTrack(r.x, r.z);",
  "  return { name: name, d0: d0, dist: end.dist, minDist: minDist, reverseT: reverseT, blocked: noseBlocked(r), speed: r.speed };",
  "}",
  "function buildWideLoop() {",
  "  resetPathCursor();",
  "  clearPit();",
  "  pathLine(160, 'start');",
  "  pathArc(44, 90, 'the90');",
  "  pathLine(90, 'short');",
  "  pathArc(44, 180, 'hairpin');",
  "  pathLine(160, 'north');",
  "  pathArc(44, 90, 'the90');",
  "  pathLine(90, 'short');",
  "  pathArc(22, 90, 'the90');",
  "  autoClosePath();",
  "}",
].join("\n");

function buildSim() {
  try {
    return new Function(code)();
  } catch (e) {
    console.error(code.split("\n").slice(0, 40).join("\n"));
    throw e;
  }
}

module.exports = { buildSim: buildSim, src: src, sliceFn: sliceFn, sliceAssign: sliceAssign };
